complete -c hyprfreeze -s h -l help -d "show help message"
complete -c hyprfreeze -s a -l active -d "toggle suspend by active window"
complete -c hyprfreeze -s p -l pid -d "toggle suspend by process id" -x -a "(__fish_complete_pids)"
complete -c hyprfreeze -s n -l name -d "toggle suspend by process name/command" -x -a "(ps -e -o comm= | sort -u)"
complete -c hyprfreeze -s r -l prop -d "toggle suspend by clicking on window"
complete -c hyprfreeze -s s -l silent -d "don't send notification"
complete -c hyprfreeze -s t -l notif-timeout -d "notification timeout in milliseconds" -x
complete -c hyprfreeze -l dry-run -d "doesn't actually suspend/resume a process"
complete -c hyprfreeze -l debug -d "enable debug mode"
complete -c hyprfreeze -l no-xorg-workaround -d "skip the XWayland mouse capture workaround"